//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenceLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int Admin_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string city { get; set; }
        public int zip { get; set; }
        public string street { get; set; }
        public int street_number { get; set; }
        public string phone_number { get; set; }
    }
}
