//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenceLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string city { get; set; }
        public int zip { get; set; }
        public string street { get; set; }
        public int streetNr { get; set; }
        public string phoneNr { get; set; }
        public System.DateTime dateOfBirth { get; set; }
        public string login { get; set; }
        public string pass { get; set; }
        public string salt { get; set; }
    }
}
