//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenceLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public int Ap_Id { get; set; }
        public string patientProblem { get; set; }
        public string symptom { get; set; }
        public string advice { get; set; }
    
        public virtual Appointment Appointment { get; set; }
    }
}
