//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.PatientsServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Patient", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
    [System.SerializableAttribute()]
    public partial class Patient : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] RowVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication2.PatientsServiceRef.Appointment[] appointmentsHistoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sessionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string streetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int streetNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int zipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] RowVersion {
            get {
                return this.RowVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.RowVersionField, value) != true)) {
                    this.RowVersionField = value;
                    this.RaisePropertyChanged("RowVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication2.PatientsServiceRef.Appointment[] appointmentsHistory {
            get {
                return this.appointmentsHistoryField;
            }
            set {
                if ((object.ReferenceEquals(this.appointmentsHistoryField, value) != true)) {
                    this.appointmentsHistoryField = value;
                    this.RaisePropertyChanged("appointmentsHistory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                if ((this.dateOfBirthField.Equals(value) != true)) {
                    this.dateOfBirthField = value;
                    this.RaisePropertyChanged("dateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string login {
            get {
                return this.loginField;
            }
            set {
                if ((object.ReferenceEquals(this.loginField, value) != true)) {
                    this.loginField = value;
                    this.RaisePropertyChanged("login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pass {
            get {
                return this.passField;
            }
            set {
                if ((object.ReferenceEquals(this.passField, value) != true)) {
                    this.passField = value;
                    this.RaisePropertyChanged("pass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phoneNr {
            get {
                return this.phoneNrField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneNrField, value) != true)) {
                    this.phoneNrField = value;
                    this.RaisePropertyChanged("phoneNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sessionID {
            get {
                return this.sessionIDField;
            }
            set {
                if ((object.ReferenceEquals(this.sessionIDField, value) != true)) {
                    this.sessionIDField = value;
                    this.RaisePropertyChanged("sessionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string street {
            get {
                return this.streetField;
            }
            set {
                if ((object.ReferenceEquals(this.streetField, value) != true)) {
                    this.streetField = value;
                    this.RaisePropertyChanged("street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int streetNr {
            get {
                return this.streetNrField;
            }
            set {
                if ((this.streetNrField.Equals(value) != true)) {
                    this.streetNrField = value;
                    this.RaisePropertyChanged("streetNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int zip {
            get {
                return this.zipField;
            }
            set {
                if ((this.zipField.Equals(value) != true)) {
                    this.zipField = value;
                    this.RaisePropertyChanged("zip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Appointment", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
    [System.SerializableAttribute()]
    public partial class Appointment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] RowVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication2.PatientsServiceRef.Doctor doctorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication2.PatientsServiceRef.Patient patientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string serviceTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime timeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication2.PatientsServiceRef.Visit visitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] RowVersion {
            get {
                return this.RowVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.RowVersionField, value) != true)) {
                    this.RowVersionField = value;
                    this.RaisePropertyChanged("RowVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication2.PatientsServiceRef.Doctor doctor {
            get {
                return this.doctorField;
            }
            set {
                if ((object.ReferenceEquals(this.doctorField, value) != true)) {
                    this.doctorField = value;
                    this.RaisePropertyChanged("doctor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication2.PatientsServiceRef.Patient patient {
            get {
                return this.patientField;
            }
            set {
                if ((object.ReferenceEquals(this.patientField, value) != true)) {
                    this.patientField = value;
                    this.RaisePropertyChanged("patient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string serviceType {
            get {
                return this.serviceTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.serviceTypeField, value) != true)) {
                    this.serviceTypeField = value;
                    this.RaisePropertyChanged("serviceType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime time {
            get {
                return this.timeField;
            }
            set {
                if ((this.timeField.Equals(value) != true)) {
                    this.timeField = value;
                    this.RaisePropertyChanged("time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication2.PatientsServiceRef.Visit visit {
            get {
                return this.visitField;
            }
            set {
                if ((object.ReferenceEquals(this.visitField, value) != true)) {
                    this.visitField = value;
                    this.RaisePropertyChanged("visit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Doctor", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
    [System.SerializableAttribute()]
    public partial class Doctor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] RowVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication2.PatientsServiceRef.Appointment[] appointmentsHistoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sessionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string specialtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string streetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int streetNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int zipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] RowVersion {
            get {
                return this.RowVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.RowVersionField, value) != true)) {
                    this.RowVersionField = value;
                    this.RaisePropertyChanged("RowVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication2.PatientsServiceRef.Appointment[] appointmentsHistory {
            get {
                return this.appointmentsHistoryField;
            }
            set {
                if ((object.ReferenceEquals(this.appointmentsHistoryField, value) != true)) {
                    this.appointmentsHistoryField = value;
                    this.RaisePropertyChanged("appointmentsHistory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string login {
            get {
                return this.loginField;
            }
            set {
                if ((object.ReferenceEquals(this.loginField, value) != true)) {
                    this.loginField = value;
                    this.RaisePropertyChanged("login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pass {
            get {
                return this.passField;
            }
            set {
                if ((object.ReferenceEquals(this.passField, value) != true)) {
                    this.passField = value;
                    this.RaisePropertyChanged("pass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phoneNr {
            get {
                return this.phoneNrField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneNrField, value) != true)) {
                    this.phoneNrField = value;
                    this.RaisePropertyChanged("phoneNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sessionID {
            get {
                return this.sessionIDField;
            }
            set {
                if ((object.ReferenceEquals(this.sessionIDField, value) != true)) {
                    this.sessionIDField = value;
                    this.RaisePropertyChanged("sessionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string specialty {
            get {
                return this.specialtyField;
            }
            set {
                if ((object.ReferenceEquals(this.specialtyField, value) != true)) {
                    this.specialtyField = value;
                    this.RaisePropertyChanged("specialty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string street {
            get {
                return this.streetField;
            }
            set {
                if ((object.ReferenceEquals(this.streetField, value) != true)) {
                    this.streetField = value;
                    this.RaisePropertyChanged("street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int streetNr {
            get {
                return this.streetNrField;
            }
            set {
                if ((this.streetNrField.Equals(value) != true)) {
                    this.streetNrField = value;
                    this.RaisePropertyChanged("streetNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int zip {
            get {
                return this.zipField;
            }
            set {
                if ((this.zipField.Equals(value) != true)) {
                    this.zipField = value;
                    this.RaisePropertyChanged("zip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Visit", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
    [System.SerializableAttribute()]
    public partial class Visit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] RowVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string adviceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string patientProblemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string symptomField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] RowVersion {
            get {
                return this.RowVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.RowVersionField, value) != true)) {
                    this.RowVersionField = value;
                    this.RaisePropertyChanged("RowVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string advice {
            get {
                return this.adviceField;
            }
            set {
                if ((object.ReferenceEquals(this.adviceField, value) != true)) {
                    this.adviceField = value;
                    this.RaisePropertyChanged("advice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string patientProblem {
            get {
                return this.patientProblemField;
            }
            set {
                if ((object.ReferenceEquals(this.patientProblemField, value) != true)) {
                    this.patientProblemField = value;
                    this.RaisePropertyChanged("patientProblem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string symptom {
            get {
                return this.symptomField;
            }
            set {
                if ((object.ReferenceEquals(this.symptomField, value) != true)) {
                    this.symptomField = value;
                    this.RaisePropertyChanged("symptom");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatientFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
    [System.SerializableAttribute()]
    public partial class PatientFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaultMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaultMessage {
            get {
                return this.FaultMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultMessageField, value) != true)) {
                    this.FaultMessageField = value;
                    this.RaisePropertyChanged("FaultMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppointmentFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
    [System.SerializableAttribute()]
    public partial class AppointmentFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaultMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaultMessage {
            get {
                return this.FaultMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultMessageField, value) != true)) {
                    this.FaultMessageField = value;
                    this.RaisePropertyChanged("FaultMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PatientsServiceRef.IPatientService")]
    public interface IPatientService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPatientService/GetPatient", ReplyAction="http://tempuri.org/IPatientService/GetPatientResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebApplication2.PatientsServiceRef.PatientFault), Action="http://tempuri.org/IPatientService/GetPatientPatientFaultFault", Name="PatientFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
        WebApplication2.PatientsServiceRef.Patient GetPatient(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPatientService/GetPatient", ReplyAction="http://tempuri.org/IPatientService/GetPatientResponse")]
        System.Threading.Tasks.Task<WebApplication2.PatientsServiceRef.Patient> GetPatientAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPatientService/UpdatePatient", ReplyAction="http://tempuri.org/IPatientService/UpdatePatientResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebApplication2.PatientsServiceRef.PatientFault), Action="http://tempuri.org/IPatientService/UpdatePatientPatientFaultFault", Name="PatientFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
        WebApplication2.PatientsServiceRef.UpdatePatientResponse UpdatePatient(WebApplication2.PatientsServiceRef.UpdatePatientRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPatientService/UpdatePatient", ReplyAction="http://tempuri.org/IPatientService/UpdatePatientResponse")]
        System.Threading.Tasks.Task<WebApplication2.PatientsServiceRef.UpdatePatientResponse> UpdatePatientAsync(WebApplication2.PatientsServiceRef.UpdatePatientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPatientService/SavePatient", ReplyAction="http://tempuri.org/IPatientService/SavePatientResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebApplication2.PatientsServiceRef.PatientFault), Action="http://tempuri.org/IPatientService/SavePatientPatientFaultFault", Name="PatientFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
        WebApplication2.PatientsServiceRef.SavePatientResponse SavePatient(WebApplication2.PatientsServiceRef.SavePatientRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPatientService/SavePatient", ReplyAction="http://tempuri.org/IPatientService/SavePatientResponse")]
        System.Threading.Tasks.Task<WebApplication2.PatientsServiceRef.SavePatientResponse> SavePatientAsync(WebApplication2.PatientsServiceRef.SavePatientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPatientService/GetAllpatients", ReplyAction="http://tempuri.org/IPatientService/GetAllpatientsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebApplication2.PatientsServiceRef.PatientFault), Action="http://tempuri.org/IPatientService/GetAllpatientsPatientFaultFault", Name="PatientFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
        WebApplication2.PatientsServiceRef.Patient[] GetAllpatients();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPatientService/GetAllpatients", ReplyAction="http://tempuri.org/IPatientService/GetAllpatientsResponse")]
        System.Threading.Tasks.Task<WebApplication2.PatientsServiceRef.Patient[]> GetAllpatientsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPatientService/GetAppointmentsHistoryPatient", ReplyAction="http://tempuri.org/IPatientService/GetAppointmentsHistoryPatientResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebApplication2.PatientsServiceRef.AppointmentFault), Action="http://tempuri.org/IPatientService/GetAppointmentsHistoryPatientAppointmentFaultF" +
            "ault", Name="AppointmentFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
        WebApplication2.PatientsServiceRef.GetAppointmentsHistoryPatientResponse GetAppointmentsHistoryPatient(WebApplication2.PatientsServiceRef.GetAppointmentsHistoryPatientRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPatientService/GetAppointmentsHistoryPatient", ReplyAction="http://tempuri.org/IPatientService/GetAppointmentsHistoryPatientResponse")]
        System.Threading.Tasks.Task<WebApplication2.PatientsServiceRef.GetAppointmentsHistoryPatientResponse> GetAppointmentsHistoryPatientAsync(WebApplication2.PatientsServiceRef.GetAppointmentsHistoryPatientRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdatePatient", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdatePatientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.PatientsServiceRef.Patient Patient;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public UpdatePatientRequest() {
        }
        
        public UpdatePatientRequest(WebApplication2.PatientsServiceRef.Patient Patient, string message) {
            this.Patient = Patient;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdatePatientResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdatePatientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool UpdatePatientResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public WebApplication2.PatientsServiceRef.Patient Patient;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string message;
        
        public UpdatePatientResponse() {
        }
        
        public UpdatePatientResponse(bool UpdatePatientResult, WebApplication2.PatientsServiceRef.Patient Patient, string message) {
            this.UpdatePatientResult = UpdatePatientResult;
            this.Patient = Patient;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SavePatient", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SavePatientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.PatientsServiceRef.Patient patient;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public SavePatientRequest() {
        }
        
        public SavePatientRequest(WebApplication2.PatientsServiceRef.Patient patient, string message) {
            this.patient = patient;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SavePatientResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SavePatientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SavePatientResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public WebApplication2.PatientsServiceRef.Patient patient;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string message;
        
        public SavePatientResponse() {
        }
        
        public SavePatientResponse(bool SavePatientResult, WebApplication2.PatientsServiceRef.Patient patient, string message) {
            this.SavePatientResult = SavePatientResult;
            this.patient = patient;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAppointmentsHistoryPatient", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAppointmentsHistoryPatientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public GetAppointmentsHistoryPatientRequest() {
        }
        
        public GetAppointmentsHistoryPatientRequest(int id, string message) {
            this.id = id;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAppointmentsHistoryPatientResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAppointmentsHistoryPatientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.PatientsServiceRef.Patient GetAppointmentsHistoryPatientResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public GetAppointmentsHistoryPatientResponse() {
        }
        
        public GetAppointmentsHistoryPatientResponse(WebApplication2.PatientsServiceRef.Patient GetAppointmentsHistoryPatientResult, string message) {
            this.GetAppointmentsHistoryPatientResult = GetAppointmentsHistoryPatientResult;
            this.message = message;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPatientServiceChannel : WebApplication2.PatientsServiceRef.IPatientService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PatientServiceClient : System.ServiceModel.ClientBase<WebApplication2.PatientsServiceRef.IPatientService>, WebApplication2.PatientsServiceRef.IPatientService {
        
        public PatientServiceClient() {
        }
        
        public PatientServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PatientServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PatientServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PatientServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebApplication2.PatientsServiceRef.Patient GetPatient(int id) {
            return base.Channel.GetPatient(id);
        }
        
        public System.Threading.Tasks.Task<WebApplication2.PatientsServiceRef.Patient> GetPatientAsync(int id) {
            return base.Channel.GetPatientAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication2.PatientsServiceRef.UpdatePatientResponse WebApplication2.PatientsServiceRef.IPatientService.UpdatePatient(WebApplication2.PatientsServiceRef.UpdatePatientRequest request) {
            return base.Channel.UpdatePatient(request);
        }
        
        public bool UpdatePatient(ref WebApplication2.PatientsServiceRef.Patient Patient, ref string message) {
            WebApplication2.PatientsServiceRef.UpdatePatientRequest inValue = new WebApplication2.PatientsServiceRef.UpdatePatientRequest();
            inValue.Patient = Patient;
            inValue.message = message;
            WebApplication2.PatientsServiceRef.UpdatePatientResponse retVal = ((WebApplication2.PatientsServiceRef.IPatientService)(this)).UpdatePatient(inValue);
            Patient = retVal.Patient;
            message = retVal.message;
            return retVal.UpdatePatientResult;
        }
        
        public System.Threading.Tasks.Task<WebApplication2.PatientsServiceRef.UpdatePatientResponse> UpdatePatientAsync(WebApplication2.PatientsServiceRef.UpdatePatientRequest request) {
            return base.Channel.UpdatePatientAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication2.PatientsServiceRef.SavePatientResponse WebApplication2.PatientsServiceRef.IPatientService.SavePatient(WebApplication2.PatientsServiceRef.SavePatientRequest request) {
            return base.Channel.SavePatient(request);
        }
        
        public bool SavePatient(ref WebApplication2.PatientsServiceRef.Patient patient, ref string message) {
            WebApplication2.PatientsServiceRef.SavePatientRequest inValue = new WebApplication2.PatientsServiceRef.SavePatientRequest();
            inValue.patient = patient;
            inValue.message = message;
            WebApplication2.PatientsServiceRef.SavePatientResponse retVal = ((WebApplication2.PatientsServiceRef.IPatientService)(this)).SavePatient(inValue);
            patient = retVal.patient;
            message = retVal.message;
            return retVal.SavePatientResult;
        }
        
        public System.Threading.Tasks.Task<WebApplication2.PatientsServiceRef.SavePatientResponse> SavePatientAsync(WebApplication2.PatientsServiceRef.SavePatientRequest request) {
            return base.Channel.SavePatientAsync(request);
        }
        
        public WebApplication2.PatientsServiceRef.Patient[] GetAllpatients() {
            return base.Channel.GetAllpatients();
        }
        
        public System.Threading.Tasks.Task<WebApplication2.PatientsServiceRef.Patient[]> GetAllpatientsAsync() {
            return base.Channel.GetAllpatientsAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication2.PatientsServiceRef.GetAppointmentsHistoryPatientResponse WebApplication2.PatientsServiceRef.IPatientService.GetAppointmentsHistoryPatient(WebApplication2.PatientsServiceRef.GetAppointmentsHistoryPatientRequest request) {
            return base.Channel.GetAppointmentsHistoryPatient(request);
        }
        
        public WebApplication2.PatientsServiceRef.Patient GetAppointmentsHistoryPatient(int id, ref string message) {
            WebApplication2.PatientsServiceRef.GetAppointmentsHistoryPatientRequest inValue = new WebApplication2.PatientsServiceRef.GetAppointmentsHistoryPatientRequest();
            inValue.id = id;
            inValue.message = message;
            WebApplication2.PatientsServiceRef.GetAppointmentsHistoryPatientResponse retVal = ((WebApplication2.PatientsServiceRef.IPatientService)(this)).GetAppointmentsHistoryPatient(inValue);
            message = retVal.message;
            return retVal.GetAppointmentsHistoryPatientResult;
        }
        
        public System.Threading.Tasks.Task<WebApplication2.PatientsServiceRef.GetAppointmentsHistoryPatientResponse> GetAppointmentsHistoryPatientAsync(WebApplication2.PatientsServiceRef.GetAppointmentsHistoryPatientRequest request) {
            return base.Channel.GetAppointmentsHistoryPatientAsync(request);
        }
    }
}
